apiVersion: v1
kind: Secret
metadata:
  name: teslamateagile-secrets
type: Opaque
stringData:
  connectionString: '{{connectionString}}'
  regionCode: '{{regionCode}}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teslamateagile
spec:
  selector:
    matchLabels:
      app: teslamateagile
  replicas: 1
  template:
    metadata:
      labels:
        app: teslamateagile
    spec:
      containers:
        - name: teslamateagile
          image: mattjeanes/teslamateagile:latest
          env:
            - name: ConnectionStrings__TeslaMate
              valueFrom:
                secretKeyRef:
                  name: teslamateagile-secrets
                  key: connectionString
            - name: TeslaMate__UpdateIntervalSeconds
              value: '300'
            - name: TeslaMate__GeofenceId
              value: '1'
            - name: TeslaMate__Phases
              value: '1'
            - name: Octopus__RegionCode
              valueFrom:
                secretKeyRef:
                  name: teslamateagile-secrets
                  key: regionCode
