apiVersion: v1
kind: Secret
metadata:
  name: teslamateagile
  labels:
    app: teslamateagile
type: Opaque
stringData:
  DATABASE_PASS: {{ required "database.pass is required" .Values.database.pass | quote }}
  {{- if eq .Values.energyProvider "Tibber" }}
  Tibber__AccessToken: {{ required "tibber.accessToken is required" .Values.tibber.accessToken | quote }}
  {{- end }}
  {{- if eq .Values.energyProvider "HomeAssistant" }}
  HomeAssistant__AccessToken: {{ required "homeAssistant.accessToken is required" .Values.homeAssistant.accessToken | quote }}
  {{- end }}