name: Build
on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        dockerfile: ./TeslaMateAgile/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: mattjeanes/teslamateagile
        tags: latest
        tag_with_ref: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
      
    - name: Build .NET Core project
      run: dotnet publish ./TeslaMateAgile/TeslaMateAgile.csproj --output ./output/TeslaMateAgile
    
    - name: Zip project
      run: |
        cd ./output/TeslaMateAgile
        zip -r ../TeslaMateAgile.zip .
        cd ../../
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: TeslaMateAgile
        path: ./output/TeslaMateAgile
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
      if: startsWith(github.ref, 'refs/tags/')
      
    - name: Upload a Release Asset
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/TeslaMateAgile.zip
        asset_name: TeslaMateAgile.zip
        asset_content_type: application/zip
      if: startsWith(github.ref, 'refs/tags/')
      
    - name: Azure Kubernetes set context
      uses: Azure/aks-set-context@v1
      with:
        creds: ${{ secrets.KUBERNETES_AZURE_CREDENTIALS }}
        resource-group: ${{ secrets.KUBERNETES_AZURE_RESOURCEGROUPNAME }}
        cluster-name: ${{ secrets.KUBERNETES_AZURE_CLUSTERNAME }}
      if: startsWith(github.ref, 'refs/tags/')
      
    - name: Deploy to Kubernetes cluster
      uses: Azure/k8s-deploy@v1
      with:
        namespace: ${{ secrets.KUBERNETES_NAMESPACE }}
        manifests: ./kube-deploy.yml
        images: 'mattjeanes/teslamateagile:${{ github.ref }}'
      if: startsWith(github.ref, 'refs/tags/')
