name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --file ./TeslaMateAgile/Dockerfile . --tag teslamateagile:$(date +%s) --tag teslamateagile:latest
    - name: Build .NET Core project
      run: dotnet publish ./TeslaMateAgile/TeslaMateAgile.csproj --output /TeslaMateAgile
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: TeslaMateAgile
        path: /TeslaMateAgile
